version: '3'

services:
  app:
    build: .
    depends_on:
      -db
    environment:
      - POSTGRES_HOST=db
      - POSTGREES_DB=postgres
    ports:
      - 8000:8000

  db:
    image: postgres:9.6
    environment:
      - POSTGREES_DB=postgres
      - POSTGREES_USER=postgres
      - POSTGREES_PASSWORD=postgres
    ports:
      - 5432:5432
    
    valumes:
      - ./data/db:/var/lib/postgresql/data