# Generated by Django 4.0.4 on 2022-07-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_actor_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.IntegerField(default=1),
        ),
    ]
