# Generated by Django 4.0.4 on 2022-07-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_alter_actor_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(default='1950-01-01'),
        ),
    ]
